login:
    pattern:   /login
    defaults:  { _controller: FfDemoBundle:Login:entrar }
login_check:
    pattern:   /login_check


ff_demo_homepage:
    path:       /generalinicio
    defaults: { _controller: FfDemoBundle:Default:mostrar }


Vencer:
    path:       /generalvencer/
    defaults: { _controller: FfDemoBundle:Default:mostrar_vencer }

Formulario:
    path:       /generalformulario/
    defaults:  { _controller: FfDemoBundle:Matricular:mostrar_formulario }


Cuentas:
    path:       /generalcuentas/
    defaults:  { _controller: FfDemoBundle:Default:mostrarcuentas }

Salida:
    path:       /generalsalida/
    defaults:  { _controller: FfDemoBundle:Default:mostrar_IngresarSalida }

Ingreso:
    path:       /generalingreso/
    defaults:  { _controller: FfDemoBundle:Default:mostrar_IngresarIngreso }



alumno:
    path:      /generalalumno/{id}
    defaults:  { _controller: FfDemoBundle:DetalleAlumno:mostrar_alumno}


asistencia:
    path:      /generalalumno2/{id}
    defaults:  { _controller: FfDemoBundle:DetalleAlumno:mostrar_alumno_asistencia}

editar:
    path:      /generaleditar/{id}
    defaults:  { _controller: FfDemoBundle:DetalleAlumno:editar}







estadistica:
    path:      /generalestadistica/
    defaults:  { _controller: FfDemoBundle:Estadistica:mostrar_formulario}









Busqueda:
    path:      /generalbusqueda/
    defaults:  { _controller: FfDemoBundle:Busqueda:mostrar_formulario}

logout:
    path:   /logout



